import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import Grid from "@mui/material/Grid";
import dynamic from "next/dynamic";
import { useDropzone } from "react-dropzone";
import React, { useState, useEffect, useMemo } from "react";
// export default function Home() {
//   return (
//       <CustomImageEditor/>
//   )
// }
const DynamicComponentWithNoSSR = dynamic(
  () => import("../component/image-editor"),
  { ssr: false }
);

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SRE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box>
          <Grid container spacing={2} className={styles.mainGrid}>
            <Grid item xs={12} className={styles.editContainer}>
              <DynamicComponentWithNoSSR />
            </Grid>
          </Grid>
        </Box>
      </main>

      <footer className={styles.footer}>
        <Typography
          variant="h6"
          sx={{
            color: "#2E1114",
            fontWeight: "bold",
            textAlign: "left",
          }}
          component="div"
          gutterBottom
        >
          Made with ❤️ by Ermiyas Zeleke
        </Typography>
      </footer>
    </div>
  );
}
